Update CI

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -92,13 +92,19 @@ jobs:
       - shell: "bash"
         run: | # Installed packages and caches are exported for use as a cache in the next workflow run
           set -ex
+          [[ -d .cache ]] || mkdir -p .cache
+          [[ -d .cache/sccache ]] || mkdir -p .cache/sccache
+          echo "SCCACHE_DIR=$(pwd)/.cache/sccache" >> $GITHUB_ENV # Does this work with windows paths?
+          echo "SCCACHE_CACHE_SIZE=5G" >> $GITHUB_ENV # More than enough to keep the most recent project cached (as vcpkg's installed directory is copied directly)
+          sudo rm -rf /usr/share/dotnet || true # Frees ~17GB of otherwise unused space (see github.com/easimon/maximize-build-space for more tricks)
+          
           echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token
-          last_workflow_id=$(gh run list --workflow="${{ github.workflow }}" --branch="${{ github.ref_name }}" --status=completed --json databaseId,conclusion --jq '[.[] | select(.conclusion != "cancelled")]' | grep -Eo '"databaseId":[0-9]+' | sed 's/"databaseId"://g' | tail -n 1)
+          last_workflow_id=$(gh run list --workflow="${{ github.workflow }}" --branch="${{ github.ref_name }}" --status=completed --json databaseId,conclusion --limit 1 --jq '[.[] | select(.conclusion != "cancelled" and .conclusion != "")][0].databaseId')
           gh run download "$last_workflow_id" --name "vcpkg-installed-${{ matrix.target.vcpkg_triplet }}-${{ matrix.target-type }}-${{ matrix.float-precision }}" || \
               echo "::warning ::Failed to download and extract previous vcpkg installed artifacts, skipping cache..."
+          
           find vcpkg/installed/ || echo "vcpkg/installed/ not found"  # For debugging purposes, to see if the cache was restored
-          echo "SCCACHE_DIR=${{ github.workspace }}/.cache/sccache" >> $GITHUB_ENV
-          echo "SCCACHE_CACHE_SIZE=1G" >> $GITHUB_ENV # Just enough to keep the most recent project cached (as vcpkg's installed directory is copied directly)
+          find .cache/sccache/ || echo ".cache/sccache/ not found"  # For debugging purposes, to see if the cache was restored
       # </Cache restore>
 
       # <Install and build>
