Update CI

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -98,6 +98,8 @@ jobs:
       # <Install and build>
       - shell: "bash"
         run: | # HACK: Customize the vcpkg install of the main repo package with custom CMAKE_ARGS
+          set -ex
+          echo "$__OPENCASCADE_GD_CMAKE_ARGS" >__OPENCASCADE_GD_CMAKE_ARGS # Alternative way to pass the variable (required for windows)
           "$VCPKG_ROOT/bootstrap-vcpkg${{matrix.target.os == 'windows-2025' && '.bat' || '.sh'}}"
           "$VCPKG_ROOT/vcpkg${{matrix.target.os == 'windows-2025' && '.exe' || ''}}" remove opencascade-gd --classic || true  # Avoid caching too much
           "$VCPKG_ROOT/vcpkg${{matrix.target.os == 'windows-2025' && '.exe' || ''}}" install opencascade-gd --classic
