Update CI

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -79,15 +79,7 @@ jobs:
           echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token
           last_workflow_id=$(gh run list --workflow="${{ github.workflow }}" --branch="${{ github.ref_name }}" --status=completed --json databaseId --limit 1 --jq '.[0].databaseId')
           gh run download "$last_workflow_id" --name "build-${{ matrix.target.vcpkg_triplet }}-${{ matrix.target-type }}-${{ matrix.float-precision }}" || \
-          echo "::warning ::Failed to download and extract previous build artifacts, skipping cache..."
-          # Create a cache directory for vcpkg binary sources
-          [ -d .vcpkg-cache ] || mkdir .vcpkg-cache
-          abs_path=$(realpath .vcpkg-cache)
-          # Check if WSL environment (wslpath expects /mnt/c/ style paths)
-          if [ ${{ runner.os }} == 'Windows' ]; then # Probably Git Bash or MSYS on Windows: convert /c/Users/... to C:\Users\...
-            abs_path=$(echo "$abs_path" | sed -E 's#^/([a-z])/#\U\1:\\#I; s#/#\\#g')
-          fi
-          echo "VCPKG_BINARY_SOURCES=clear;files,${abs_path},readwrite" >> $GITHUB_ENV
+              echo "::warning ::Failed to download and extract previous build artifacts, skipping cache..."
       # </Use previous build artifacts as a cache>
 
       # <Install and build>
@@ -98,6 +90,7 @@ jobs:
           -DGODOTCPP_PRECISION=${{ matrix.target.float_precision }} \
           ${{ env.cmake_extra_args }}" >> $GITHUB_ENV
           "$VCPKG_ROOT/bootstrap-vcpkg${{matrix.target.os == 'windows-2025' && '.bat' || '.sh'}}"
+          "$VCPKG_ROOT/vcpkg${{matrix.target.os == 'windows-2025' && '.exe' || ''}}" remove opencascade-gd --classic || true  # Avoid caching too much
           "$VCPKG_ROOT/vcpkg${{matrix.target.os == 'windows-2025' && '.exe' || ''}}" install opencascade-gd --classic
         env:
           VCPKG_ROOT: "vcpkg"
@@ -113,6 +106,7 @@ jobs:
           name: "OpenCASCADE.gd-${{ matrix.target.vcpkg_triplet }}-${{ matrix.target-type }}-${{ matrix.float-precision }}"
           path: "demo/addons/OpenCASCADE.gd/**"
       - uses: "actions/upload-artifact@v4"
+        if: "always()"
         with: # Build artifacts useful for debugging in a local environment
           name: "build-${{ matrix.target.vcpkg_triplet }}-${{ matrix.target-type }}-${{ matrix.float-precision }}"
           path: ".vcpkg-cache\n./vcpkg/installed/"
