Update CI

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -92,7 +92,8 @@ jobs:
           echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token
           last_workflow_id=$(gh run list --workflow="${{ github.workflow }}" --branch="${{ github.ref_name }}" --status=completed --json databaseId --limit 1 --jq '.[0].databaseId')
           gh run download "$last_workflow_id" --name "build-${{ matrix.target.vcpkg_triplet }}-${{ matrix.target-type }}-${{ matrix.float-precision }}" || \
-              echo "::warning ::Failed to download and extract previous build artifacts, skipping cache..."
+              echo "::warning ::Failed to download and extract previous vcpkg installed artifacts, skipping cache..."
+          find vcpkg/installed/ || echo "vcpkg/installed/ not found"  # For debugging purposes, to see if the cache was restored
       # </Use previous build artifacts as a cache>
 
       # <Install and build>
@@ -119,9 +120,14 @@ jobs:
           path: "demo/addons/OpenCASCADE.gd/**"
       - uses: "actions/upload-artifact@v4"
         if: "always()"
-        with: # Build artifacts useful for debugging in a local environment
-          name: "build-${{ matrix.target.vcpkg_triplet }}-${{ matrix.target-type }}-${{ matrix.float-precision }}"
+        with: # Installed packages are exported for use as a cache in the next workflow run
+          name: "vcpkg-installed-${{ matrix.target.vcpkg_triplet }}-${{ matrix.target-type }}-${{ matrix.float-precision }}"
           path: "vcpkg/installed/"
+      - uses: "actions/upload-artifact@v4"
+        if: "always()"
+        with: # Build artifacts useful for debugging in a local environment
+          name: "vcpkg-buildtree-logs-${{ matrix.target.vcpkg_triplet }}-${{ matrix.target-type }}-${{ matrix.float-precision }}"
+          path: "vcpkg/buildtrees/**/*.log"
       # </Export artifacts>
   merge:
     runs-on: "ubuntu-24.04"
@@ -131,4 +137,4 @@ jobs:
         with:
           name: "OpenCASCADE.gd"
           pattern: "OpenCASCADE.gd-*"
-          delete-merged: true
+          # delete-merged: true
