Update CI

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -91,10 +91,13 @@ jobs:
           set -ex
           echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token
           last_workflow_id=$(gh run list --workflow="${{ github.workflow }}" --branch="${{ github.ref_name }}" --status=completed --json databaseId --limit 1 --jq '.[0].databaseId')
-          mkdir -p vcpkg/installed/ && cd vcpkg/installed/
+          mkdir tmp_cache && cd tmp_cache
           gh run download "$last_workflow_id" --name "build-${{ matrix.target.vcpkg_triplet }}-${{ matrix.target-type }}-${{ matrix.float-precision }}" || \
               echo "::warning ::Failed to download and extract previous vcpkg installed artifacts, skipping cache..."
-          find . || echo "vcpkg/installed/ not found"  # For debugging purposes, to see if the cache was restored
+          cd ..
+          [[ -d vcpkg/installed ]] || mkdir -p vcpkg/installed
+          mv tmp_cache/* vcpkg/installed/
+          find vcpkg/installed/ || echo "vcpkg/installed/ not found"  # For debugging purposes, to see if the cache was restored
       # </Use previous build artifacts as a cache>
 
       # <Install and build>
